### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by timomitchel** [DavidHoltkamp1/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [x] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The four attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [x] The four methods I chose for **Class #1** represent behaviors or actions.
- [x] I described what the methods do in **Class 1**, including which attributes they use or modify.
- [x] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message.

`When we use snake case we generally keep all words lowercase, so **current_capacity** follows the convention and looks better. Also, we generally only capitalize the names of classes, (not methods or attributes). I'm not sure if we went over that in Mod-0, but now you know!`

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [] I listed the values for each attribute of this object.
`We want the values to represent their data type. So 'Sue' for server and 4.0 for height.`
- [x] I listed the results of each method for this object.
`While you did list the results, the first two methods don't add up. One should add to current capacity and one should subtract from current capacity. Removing Sue is better represented by putting something like **server = 'Mark'** to show the new assignment.`
- [] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message.
`Committed with other files.`

Class #2 Checklist
- [x] The four attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [x] The four methods I chose for **Class #2** represent behaviors or actions.
- [x] I described what the methods do in **Class 2**, including which attributes they use or modify.
- [ ] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 
`Committed with other files.`

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [ ] I listed the values for each attribute of this object.
`Again, the data type should be represented in the value`
- [x] I listed the results of each method for this object. 
- [ ] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 
`Committed with other files.`

Overall, nice job on this assessment David. I can tell that you have understood the core concepts of Mod-0. We would like you to pay a bit more attention to detail. This is a skill that is incredibly valuable in programming, because many times the smallest details can have the largest impacts. 
Go ahead and clean up some of what I mentioned above in the feedback, and each time you make a change to a file, make a commit for that file that is separate from the rest of the files. Let David and I know if you have any questions. We'd like to see the changes implemented by 5PM Wednesday. Thanks David!

### Assessment Results
- [ ] Technical Ready
- [x] Pending
- [ ] Not Technical Ready
